kind: Deployment 
apiVersion: apps/v1 
metadata:
  name: flask-app-deployment
  namespace: flask-space
  labels:
    app: flask 

spec: 
  replicas: 3
  selector:
    matchLabels:
      app: flask 
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-container
          image: sharmaaakash170/flaskapp:latest
          ports:
            - containerPort: 5000 