apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-ns
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP 
